/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: .\adder.i

package adder

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stddef.h>
#include <stdint.h>


typedef ptrdiff_t intgo;
typedef size_t uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_adder_254818562f35f8db(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_adder_254818562f35f8db(swig_intgo arg1);
extern uintptr_t _wrap_new_Adder_adder_254818562f35f8db(void);
extern void _wrap_Adder_Add_adder_254818562f35f8db(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Adder_Get_adder_254818562f35f8db(uintptr_t arg1);
extern void _wrap_delete_Adder_adder_254818562f35f8db(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


func getSwigcptr(v interface { Swigcptr() uintptr }) uintptr {
	if v == nil {
		return 0
	}
	return v.Swigcptr()
}


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_adder_254818562f35f8db(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_adder_254818562f35f8db(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrAdder uintptr

func (p SwigcptrAdder) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrAdder) SwigIsAdder() {
}

func NewAdder() (_swig_ret Adder) {
	var swig_r Adder
	swig_r = (Adder)(SwigcptrAdder(C._wrap_new_Adder_adder_254818562f35f8db()))
	return swig_r
}

func (arg1 SwigcptrAdder) Add(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Adder_Add_adder_254818562f35f8db(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrAdder) Get() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Adder_Get_adder_254818562f35f8db(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteAdder(arg1 Adder) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_Adder_adder_254818562f35f8db(C.uintptr_t(_swig_i_0))
}

type Adder interface {
	Swigcptr() uintptr
	SwigIsAdder()
	Add(arg2 int)
	Get() (_swig_ret int)
}


