/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: .\luau.i

package luau

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stddef.h>
#include <stdint.h>


typedef ptrdiff_t intgo;
typedef size_t uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef long long swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef long long swig_type_6;
extern void _wrap_Swig_free_luau_9ebb29ea21602f5a(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_luau_9ebb29ea21602f5a(swig_intgo arg1);
extern swig_intgo _wrap_luau_load_luau_9ebb29ea21602f5a(uintptr_t arg1, swig_type_1 arg2, swig_type_2 arg3, swig_type_3 arg4, swig_intgo arg5);
extern swig_type_4 _wrap_luau_compile_luau_9ebb29ea21602f5a(swig_type_5 arg1, swig_type_6 arg2, uintptr_t arg3, swig_voidp arg4);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


func getSwigcptr(v interface { Swigcptr() uintptr }) uintptr {
	if v == nil {
		return 0
	}
	return v.Swigcptr()
}


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_luau_9ebb29ea21602f5a(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_luau_9ebb29ea21602f5a(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Luau_load(arg1 Lua_State, arg2 string, arg3 string, arg4 int64, arg5 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_luau_load_luau_9ebb29ea21602f5a(C.uintptr_t(_swig_i_0), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_2)), C.swig_type_3(_swig_i_3), C.swig_intgo(_swig_i_4)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func Luau_compile(arg1 string, arg2 int64, arg3 Lua_CompileOptions, arg4 *int64) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := getSwigcptr(arg3)
	_swig_i_3 := arg4
	swig_r_p := C._wrap_luau_compile_luau_9ebb29ea21602f5a(*(*C.swig_type_5)(unsafe.Pointer(&_swig_i_0)), C.swig_type_6(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_voidp(_swig_i_3))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}


type SwigcptrLua_CompileOptions uintptr
type Lua_CompileOptions interface {
	Swigcptr() uintptr;
}
func (p SwigcptrLua_CompileOptions) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrLua_State uintptr
type Lua_State interface {
	Swigcptr() uintptr;
}
func (p SwigcptrLua_State) Swigcptr() uintptr {
	return uintptr(p)
}

